modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#logoFile="${mod_id}.png"
#credits=""
authors="${mod_authors}"
displayTest="IGNORE_SERVER_VERSION"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="tacz"
mandatory=true
versionRange="[1.0.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="airstrike"
mandatory=true
versionRange="[1.0.0,1.1.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="chloride"
mandatory=false
versionRange = "[1.7.1,)"
ordering="AFTER"
side="CLIENT"

#[modproperties.${mod_id}]
#catalogueImageIcon = "${mod_id}.png"
